import os
import requests
import re
import json


def read_config_file(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    return content


def extract_rule_set_urls(content):
    pattern = r'rule_set_urls=\(\n([\s\S]*?)\n\)'
    match = re.search(pattern, content)
    if match:
        urls_str = match.group(1)
        urls = [url.strip().strip('"') for url in urls_str.split('\n') if url.strip()]
        return urls
    return []


def fetch_rule_urls(rule_set_urls):
    rule_urls = []
    headers = {
        'Authorization': f'token {os.environ.get("GITHUB_API_TOKEN")}'
    }
    response = requests.get('https://api.github.com/repos/blackmatrix7/ios_rule_script/contents/rule/Clash?ref=master',
                            headers=headers)
    if response.status_code == 200:
        try:
            data = response.json()
            if isinstance(data, list):
                # 添加需要忽略的路径
                ignore_paths = [
                    'rule/Clash/9News/',
                    'rule/Clash/9to5/',
                    'rule/Clash/ABC/',
                    'rule/Clash/AFP/',
                    'rule/Clash/AMD/',
                    'rule/Clash/AOL/',
                    'rule/Clash/ATTWatchTV/',
                    'rule/Clash/AbemaTV/',
                    'rule/Clash/Acer/',
                    'rule/Clash/AdGuardSDNSFilter/',
                    'rule/Clash/Adidas/',
                    'rule/Clash/Adobe/',
                    'rule/Clash/AdobeActivation/',
                    'rule/Clash/Advertising/',
                    'rule/Clash/AdvertisingLite/',
                    'rule/Clash/AdvertisingMiTV/',
                    'rule/Clash/AdvertisingTest/',
                    'rule/Clash/Akamai/',
                    'rule/Clash/All4/',
                    'rule/Clash/Amazon/',
                    'rule/Clash/AmazonIP/',
                    'rule/Clash/AmazonPrimeVideo/',
                    'rule/Clash/Americasvoice/',
                    'rule/Clash/Apkpure/',
                    'rule/Clash/AppStore/',
                    'rule/Clash/Apple/',
                    'rule/Clash/AppleDaily/',
                    'rule/Clash/AppleDev/',
                    'rule/Clash/AppleFirmware/',
                    'rule/Clash/AppleHardware/',
                    'rule/Clash/AppleID/',
                    'rule/Clash/AppleMail/',
                    'rule/Clash/AppleMedia/',
                    'rule/Clash/AppleMusic/',
                    'rule/Clash/AppleNews/',
                    'rule/Clash/AppleProxy/',
                    'rule/Clash/AppleTV/',
                    'rule/Clash/Arphic/',
                    'rule/Clash/AsianMedia/',
                    'rule/Clash/Assassin\'sCreed/',
                    'rule/Clash/Atlassian/',
                    'rule/Clash/Atomdata/',
                    'rule/Clash/BBC/',
                    'rule/Clash/BMW/',
                    'rule/Clash/Bahamut/',
                    'rule/Clash/Battle/',
                    'rule/Clash/Beats/',
                    'rule/Clash/Bestbuy/',
                    'rule/Clash/BiliBiliIntl/',
                    'rule/Clash/Binance/',
                    'rule/Clash/Bing/',
                    'rule/Clash/Blizzard/',
                    'rule/Clash/BlockHttpDNS/',
                    'rule/Clash/Bloomberg/',
                    'rule/Clash/Blued/',
                    'rule/Clash/BoXun/',
                    'rule/Clash/BrightCove/',
                    'rule/Clash/BritboxUK/',
                    'rule/Clash/Buypass/',
                    'rule/Clash/CBS/',
                    'rule/Clash/CHT/',
                    'rule/Clash/CNN/',
                    'rule/Clash/CWSeed/',
                    'rule/Clash/CableTV/',
                    'rule/Clash/Cake/',
                    'rule/Clash/Canon/',
                    'rule/Clash/China/',
                    'rule/Clash/ChinaIPs/',
                    'rule/Clash/ChinaIPsBGP/',
                    'rule/Clash/ChinaMax/',
                    'rule/Clash/ChinaMaxNoIP/',
                    'rule/Clash/ChinaMaxNoMedia/',
                    'rule/Clash/ChinaNoMedia/',
                    'rule/Clash/ChinaTest/',
                    'rule/Clash/Chromecast/',
                    'rule/Clash/Cisco/',
                    'rule/Clash/Classic/',
                    'rule/Clash/Claude/',
                    'rule/Clash/Cloudflare/',
                    'rule/Clash/Clubhouse/',
                    'rule/Clash/ClubhouseIP/',
                    'rule/Clash/Comodo/',
                    'rule/Clash/Cryptocurrency/',
                    'rule/Clash/DAZN/',
                    'rule/Clash/DMM/',
                    'rule/Clash/DNS/',
                    'rule/Clash/Dailymail/',
                    'rule/Clash/Dailymotion/',
                    'rule/Clash/Deezer/',
                    'rule/Clash/Dell/',
                    'rule/Clash/Developer/',
                    'rule/Clash/DiabloIII/',
                    'rule/Clash/DigiCert/',
                    'rule/Clash/DigitalOcean/',
                    'rule/Clash/Direct/',
                    'rule/Clash/Discord/',
                    'rule/Clash/DiscoveryPlus/',
                    'rule/Clash/Disney/',
                    'rule/Clash/Disqus/',
                    'rule/Clash/Docker/',
                    'rule/Clash/Domob/',
                    'rule/Clash/Dood/',
                    'rule/Clash/Download/',
                    'rule/Clash/Dropbox/',
                    'rule/Clash/DtDNS/',
                    'rule/Clash/Dubox/',
                    'rule/Clash/Duckduckgo/',
                    'rule/Clash/DynDNS/',
                    'rule/Clash/Dynu/',
                    'rule/Clash/EA/',
                    'rule/Clash/EHGallery/',
                    'rule/Clash/EasyPrivacy/',
                    'rule/Clash/Embl/',
                    'rule/Clash/Emby/',
                    'rule/Clash/Emojipedia/',
                    'rule/Clash/EncoreTVB/',
                    'rule/Clash/Epic/',
                    'rule/Clash/Espn/',
                    'rule/Clash/FOXNOW/',
                    'rule/Clash/FOXPlus/',
                    'rule/Clash/Facebook/',
                    'rule/Clash/Faronics/',
                    'rule/Clash/FindMy/',
                    'rule/Clash/FitnessPlus/',
                    'rule/Clash/FlipBoard/',
                    'rule/Clash/Fox/',
                    'rule/Clash/FuboTV/',
                    'rule/Clash/Funshion/',
                    'rule/Clash/Game/',
                    'rule/Clash/Garena/',
                    'rule/Clash/Gettyimages/',
                    'rule/Clash/Gigabyte/',
                    'rule/Clash/GitBook/',
                    'rule/Clash/GitHub/',
                    'rule/Clash/GitLab/',
                    'rule/Clash/Global/',
                    'rule/Clash/GlobalMedia/',
                    'rule/Clash/GlobalScholar/',
                    'rule/Clash/GlobalSign/',
                    'rule/Clash/Gog/',
                    'rule/Clash/Google/',
                    'rule/Clash/GoogleDrive/',
                    'rule/Clash/GoogleEarth/',
                    'rule/Clash/GoogleFCM/',
                    'rule/Clash/GoogleSearch/',
                    'rule/Clash/GoogleVoice/',
                    'rule/Clash/Gucci/',
                    'rule/Clash/HBO/',
                    'rule/Clash/HBOAsia/',
                    'rule/Clash/HBOHK/',
                    'rule/Clash/HBOUSA/',
                    'rule/Clash/HKBN/',
                    'rule/Clash/HKedcity/',
                    'rule/Clash/HP/',
                    'rule/Clash/HWTV/',
                    'rule/Clash/HamiVideo/',
                    'rule/Clash/HashiCorp/',
                    'rule/Clash/Hearthstone/',
                    'rule/Clash/HeroesoftheStorm/',
                    'rule/Clash/Heroku/',
                    'rule/Clash/HibyMusic/',
                    'rule/Clash/Hijacking/',
                    'rule/Clash/HoYoverse/',
                    'rule/Clash/Huffpost/',
                    'rule/Clash/Hulu/',
                    'rule/Clash/HuluJP/',
                    'rule/Clash/HuluUSA/',
                    'rule/Clash/IBM/',
                    'rule/Clash/IKEA/',
                    'rule/Clash/IMDB/',
                    'rule/Clash/IPTVMainland/',
                    'rule/Clash/IPTVOther/',
                    'rule/Clash/ITV/',
                    'rule/Clash/Identrust/',
                    'rule/Clash/Imgur/',
                    'rule/Clash/Instagram/',
                    'rule/Clash/Intel/',
                    'rule/Clash/Intercom/',
                    'rule/Clash/JOOX/',
                    'rule/Clash/Japonx/',
                    'rule/Clash/Jetbrains/',
                    'rule/Clash/Jfrog/',
                    'rule/Clash/Jquery/',
                    'rule/Clash/Jsdelivr/',
                    'rule/Clash/Jwplayer/',
                    'rule/Clash/KKBOX/',
                    'rule/Clash/KKTV/',
                    'rule/Clash/KakaoTalk/',
                    'rule/Clash/Kantv/',
                    'rule/Clash/LG/',
                    'rule/Clash/Lan/',
                    'rule/Clash/LastFM/',
                    'rule/Clash/LastPass/',
                    'rule/Clash/LiTV/',
                    'rule/Clash/Limelight/',
                    'rule/Clash/Line/',
                    'rule/Clash/LineTV/',
                    'rule/Clash/LinkedIn/',
                    'rule/Clash/LivePerson/',
                    'rule/Clash/Logitech/',
                    'rule/Clash/LondonReal/',
                    'rule/Clash/MEGA/',
                    'rule/Clash/MOMOShop/',
                    'rule/Clash/MOOV/',
                    'rule/Clash/Mail/',
                    'rule/Clash/Mailru/',
                    'rule/Clash/Majsoul/',
                    'rule/Clash/Manorama/',
                    'rule/Clash/Maocloud/',
                    'rule/Clash/Marketing/',
                    'rule/Clash/McDonalds/',
                    'rule/Clash/MeWatch/',
                    'rule/Clash/Microsoft/',
                    'rule/Clash/MicrosoftEdge/',
                    'rule/Clash/Mozilla/',
                    'rule/Clash/My5/',
                    'rule/Clash/NBC/',
                    'rule/Clash/NTPService/',
                    'rule/Clash/NYPost/',
                    'rule/Clash/NYTimes/',
                    'rule/Clash/Naver/',
                    'rule/Clash/NaverTV/',
                    'rule/Clash/Netflix/',
                    'rule/Clash/Niconico/',
                    'rule/Clash/Nike/',
                    'rule/Clash/Nikkei/',
                    'rule/Clash/Nintendo/',
                    'rule/Clash/Notion/',
                    'rule/Clash/NowE/',
                    'rule/Clash/Nvidia/',
                    'rule/Clash/OP/',
                    'rule/Clash/OneDrive/',
                    'rule/Clash/OpenAI/',
                    'rule/Clash/Opera/',
                    'rule/Clash/Oreilly/',
                    'rule/Clash/Origin/',
                    'rule/Clash/Overcast/',
                    'rule/Clash/Overwatch/',
                    'rule/Clash/PBS/',
                    'rule/Clash/PCCW/',
                    'rule/Clash/PChomeTW/',
                    'rule/Clash/Pandora/',
                    'rule/Clash/PandoraTV/',
                    'rule/Clash/ParamountPlus/',
                    'rule/Clash/PayPal/',
                    'rule/Clash/Peacock/',
                    'rule/Clash/Picsee/',
                    'rule/Clash/PikPak/',
                    'rule/Clash/Pinterest/',
                    'rule/Clash/Pixiv/',
                    'rule/Clash/Pixnet/',
                    'rule/Clash/PlayStation/',
                    'rule/Clash/PotatoChat/',
                    'rule/Clash/PrimeVideo/',
                    'rule/Clash/Privacy/',
                    'rule/Clash/PrivateTracker/',
                    'rule/Clash/Protonmail/',
                    'rule/Clash/Proxy/',
                    'rule/Clash/ProxyLite/',
                    'rule/Clash/Purikonejp/',
                    'rule/Clash/Python/',
                    'rule/Clash/Qobuz/',
                    'rule/Clash/Qualcomm/',
                    'rule/Clash/QuickConnect/',
                    'rule/Clash/Qyyjt/',
                    'rule/Clash/README.md/',
                    'rule/Clash/RTHK/',
                    'rule/Clash/Rakuten/',
                    'rule/Clash/Rarbg/',
                    'rule/Clash/Razer/',
                    'rule/Clash/Reddit/',
                    'rule/Clash/RemoteDesktop/',
                    'rule/Clash/Riot/',
                    'rule/Clash/Rockstar/',
                    'rule/Clash/Salesforce/',
                    'rule/Clash/Samsung/',
                    'rule/Clash/Scaleflex/',
                    'rule/Clash/Scholar/',
                    'rule/Clash/Sectigo/',
                    'rule/Clash/Shopee/',
                    'rule/Clash/Shopify/',
                    'rule/Clash/Siri/',
                    'rule/Clash/SkyGO/',
                    'rule/Clash/Slack/',
                    'rule/Clash/Sling/',
                    'rule/Clash/SmarTone/',
                    'rule/Clash/Snap/',
                    'rule/Clash/Sony/',
                    'rule/Clash/SoundCloud/',
                    'rule/Clash/SourceForge/',
                    'rule/Clash/Spark/',
                    'rule/Clash/Speedtest/',
                    'rule/Clash/Spotify/',
                    'rule/Clash/Stackexchange/',
                    'rule/Clash/StarCraftII/',
                    'rule/Clash/Starbucks/',
                    'rule/Clash/Steam/',
                    'rule/Clash/SteamCN/',
                    'rule/Clash/SublimeText/',
                    'rule/Clash/Supercell/',
                    'rule/Clash/Synology/',
                    'rule/Clash/SystemOTA/',
                    'rule/Clash/TIDAL/',
                    'rule/Clash/TVB/',
                    'rule/Clash/TVer/',
                    'rule/Clash/TaiWanGood/',
                    'rule/Clash/TeamViewer/',
                    'rule/Clash/Teams/',
                    'rule/Clash/Telegram/',
                    'rule/Clash/TelegramNL/',
                    'rule/Clash/TelegramSG/',
                    'rule/Clash/TelegramUS/',
                    'rule/Clash/TeraBox/',
                    'rule/Clash/Tesla/',
                    'rule/Clash/TestFlight/',
                    'rule/Clash/ThomsonReuters/',
                    'rule/Clash/TikTok/',
                    'rule/Clash/Tumblr/',
                    'rule/Clash/Twitch/',
                    'rule/Clash/Twitter/',
                    'rule/Clash/U17/',
                    'rule/Clash/UBI/',
                    'rule/Clash/Ubuntu/',
                    'rule/Clash/Unity/',
                    'rule/Clash/VISA/',
                    'rule/Clash/VK/',
                    'rule/Clash/VOA/',
                    'rule/Clash/Vancl/',
                    'rule/Clash/Vercel/',
                    'rule/Clash/Verisign/',
                    'rule/Clash/Verizon/',
                    'rule/Clash/VidolTV/',
                    'rule/Clash/VikACG/',
                    'rule/Clash/Viki/',
                    'rule/Clash/Vimeo/',
                    'rule/Clash/ViuTV/',
                    'rule/Clash/Voxmedia/',
                    'rule/Clash/WIX/',
                    'rule/Clash/WeTV/',
                    'rule/Clash/Westerndigital/',
                    'rule/Clash/Whatsapp/',
                    'rule/Clash/Wikimedia/',
                    'rule/Clash/Wikipedia/',
                    'rule/Clash/WildRift/',
                    'rule/Clash/Wordpress/',
                    'rule/Clash/WorldofWarcraft/',
                    'rule/Clash/Xbox/',
                    'rule/Clash/YYeTs/',
                    'rule/Clash/Yandex/',
                    'rule/Clash/YouTube/',
                    'rule/Clash/YouTubeMusic/',
                    'rule/Clash/Zee/',
                    'rule/Clash/ZeeTV/',
                    'rule/Clash/Zendesk/',
                    'rule/Clash/ZhihuAds/',
                    'rule/Clash/Zoho/',
                    'rule/Clash/eBay/',
                    'rule/Clash/friDay/',
                    'rule/Clash/iCloud/',
                    'rule/Clash/iCloudPrivateRelay/',
                    'rule/Clash/iQIYIIntl/',
                    'rule/Clash/iTalkBB/',
                    'rule/Clash/myTVSUPER/',
                ]  # 添加需要忽略的路径
                for item in data:
                    if 'path' in item:
                        path = item['path'] + '/'
                        if not any(url for url in rule_set_urls if path in url) and path not in ignore_paths:
                            rule_urls.append(item['html_url'])
        except json.JSONDecodeError:
            pass
    return rule_urls


if __name__ == '__main__':
    china_file_path = './China/config.sh'
    china_config_content = read_config_file(china_file_path)
    china_rule_set_urls = extract_rule_set_urls(china_config_content)

    overseas_file_path = './Overseas/config.sh'
    overseas_config_content = read_config_file(overseas_file_path)
    overseas_rule_set_urls = extract_rule_set_urls(overseas_config_content)

    rule_set_urls = china_rule_set_urls + overseas_rule_set_urls
    rule_urls = fetch_rule_urls(rule_set_urls)

    for url in rule_urls:
        print(url)
