#!/usr/bin/env bash
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin

rule_set_urls=(
    "https://raw.githubusercontent.com/jLKmDMQk/Rules/master/Rules/china-sites.list"

    "rule/Clash/Kingsoft/Kingsoft.list"
    "rule/Surge/Alibaba/Alibaba_All.list"
    "rule/Surge/Baidu/Baidu.list"
    "rule/Surge/ByteDance/ByteDance.list"
    "rule/Surge/Huawei/Huawei.list"
    "rule/Surge/JingDong/JingDong.list"
    "rule/Surge/KuaiShou/KuaiShou.list"
    "rule/Surge/MeiTuan/MeiTuan.list"
    "rule/Surge/NetEase/NetEase.list"
    "rule/Surge/Pinduoduo/Pinduoduo.list"
    "rule/Surge/Sina/Sina.list"
    "rule/Surge/Sohu/Sohu.list"
    "rule/Surge/Tencent/Tencent.list"
    "rule/Surge/XiaoHongShu/XiaoHongShu.list"

    "rule/Surge/MeiZu/MeiZu.list"
    "rule/Surge/OPPO/OPPO.list"
    "rule/Surge/OnePlus/OnePlus.list"
    "rule/Surge/Vivo/Vivo.list"
    "rule/Surge/XiaoMi/XiaoMi.list"

    "rule/Surge/AcFun/AcFun.list"
    "rule/Surge/BiliBili/BiliBili.list"
    "rule/Surge/PPTV/PPTV.list"
    "rule/Surge/Youku/Youku.list"
    "rule/Surge/iQIYI/iQIYI.list"

    "rule/Surge/QiNiuYun/QiNiuYun.list"
    "rule/Surge/UCloud/UCloud.list"
    "rule/Surge/UPYun/UPYun.list"

    "rule/Surge/ABC/ABC.list"
    "rule/Surge/BOC/BOC.list"
    "rule/Surge/BOCOM/BOCOM.list"
    "rule/Surge/CCB/CCB.list"
    "rule/Surge/CEB/CEB.list"
    "rule/Surge/CGB/CGB.list"
    "rule/Surge/CMB/CMB.list"
    "rule/Surge/ICBC/ICBC.list"
    "rule/Surge/UnionPay/UnionPay.list"

    "rule/Surge/ChinaMobile/ChinaMobile.list"
    "rule/Surge/ChinaTelecom/ChinaTelecom.list"
    "rule/Surge/ChinaUnicom/ChinaUnicom.list"

    "rule/Surge/115/115.list"
    "rule/Surge/12306/12306.list"
    "rule/Surge/17173/17173.list"
    "rule/Surge/178/178.list"
    "rule/Surge/360/360.list"
    "rule/Surge/36kr/36kr.list"
    "rule/Surge/3dm/3dm.list"
    "rule/Surge/4399/4399.list"
    "rule/Surge/Anjuke/Anjuke.list"
    "rule/Surge/CSDN/CSDN.list"
    "rule/Surge/Douyu/Douyu.list"
    "rule/Surge/Geely/Geely.list"
    "rule/Surge/JueJin/JueJin.list"
    "rule/Surge/LanZouYun/LanZouYun.list"
    "rule/Surge/LeJu/LeJu.list"
    "rule/Surge/NGA/NGA.list"
    "rule/Surge/SFExpress/SFExpress.list"
    "rule/Surge/SMZDM/SMZDM.list"
    "rule/Surge/TCL/TCL.list"
    "rule/Surge/UC/UC.list"
    "rule/Surge/XueQiu/XueQiu.list"
    "rule/Surge/Xunlei/Xunlei.list"
    "rule/Surge/YiChe/YiChe.list"
    "rule/Surge/YouZan/YouZan.list"
    "rule/Surge/Zhihu/Zhihu.list"
    "rule/Surge/ifanr/ifanr.list"
)

geosite_filenames=(
    "geolocation-cn"
)
