on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 16 * * *"

env:
  TZ: Asia/Shanghai
  ENV_BRANCHS: "list,smartdns,surge,routeros,sing-box"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create directory
        working-directory: ${{ github.workspace }}
        run: |
          echo "开始创建目录..."
          IFS=',' read -ra BRANCHS <<< "${{ env.ENV_BRANCHS }}"
          for branch in "${BRANCHS[@]}"; do
            echo "创建目录: ./result/${branch}"
            mkdir -p ./result/${branch}
          done
          echo "所有目录创建完成"

      - name: Handle Data
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x ./Scripts/main.sh
          ./Scripts/main.sh

      - name: Git push assets to branchs
        working-directory: ${{ github.workspace }}
        run: |
          echo "列出 ./result 目录下的所有目录:"
          ls -la ./result/

          echo "1. 当前目录 ${PWD}"
          git config --global init.defaultBranch master
          IFS=',' read -ra BRANCHS <<< "${{ env.ENV_BRANCHS }}"
          for branch in "${BRANCHS[@]}"; do
              echo "2. 当前目录 ${PWD}"
              cd ./result/${branch} || exit 1
              echo "3. 当前目录 ${PWD}"
              git init
              git config --local user.name "github-actions[bot]"
              git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git checkout -b ${branch}
              git add .
              git commit -m "`date '+%Y%m%d%H%M'`"
              git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
              git push -f -u origin ${branch}
              cd ..
              echo "4. 当前目录 ${PWD}"
          done

      - name: Purge jsdelivr CDN
        run: |
          IFS=',' read -ra BRANCHS <<< "${{ env.ENV_BRANCHS }}"
          for branch in "${BRANCHS[@]}"; do
              cd ./result/${branch} || exit 1
              for file in $(ls); do
                curl -sSL "https://purge.jsdelivr.net/gh/${{ github.repository }}@${branch}/${file}"
              done
              cd ..
          done
